export const KNOWN_VALIDATION_KEYS = [
	"validation_email_invalid",
	"validation_password_min_length",
	"validation_name_min_length",
	"validation_student_name_required",
	"validation_student_grade_range",
	"validation_current_password_min_length",
	"validation_new_password_min_length",
	"validation_confirm_password_min_length",
	"validation_password_mismatch",
	"validation_teacher_id_required",
	"validation_verification_level_invalid",
	"validation_reject_reason_min_length",
	"validation_booking_id_required",
	"validation_setting_key_required",
	"validation_user_id_required",
	"validation_period_start_required",
	"validation_period_end_required",
	"validation_at_least_one_session_required",
	"validation_payout_id_required",
	"validation_question_min_length",
	"validation_answer_min_length",
	"validation_category_invalid",
	"validation_faq_id_required",
	"validation_student_required",
	"validation_service_required",
	"validation_start_time_required",
	"validation_cancel_reason_min_length",
	"validation_topics_covered_required",
	"validation_subject_required",
	"validation_service_type_required",
	"validation_request_title_min_length",
	"validation_request_details_too_long",
	"validation_image_url_invalid",
	"validation_request_id_required",
	"validation_offer_price_min",
	"validation_offer_duration_min",
	"validation_offer_duration_max",
	"validation_teacher_subject_required",
	"validation_teacher_grade_required",
	"validation_teacher_city_required",
	"validation_teacher_years_of_experience_invalid",
	"validation_teacher_min_hourly_rate",
	"validation_teacher_service_type_required",
	"validation_teacher_min_price",
	"validation_teacher_min_duration",
	"validation_teacher_time_format_invalid",
	"validation_teacher_slug_min_length",
	"validation_teacher_slug_max_length",
	"validation_teacher_slug_format_invalid",
	"validation_review_rating_range",
	"validation_dispute_booking_id_required",
	"validation_dispute_reason_min_length",
	"validation_dispute_reason_max_length",
	"validation_dispute_id_required",
	"validation_dispute_message_required",
	"validation_dispute_message_max_length",
	"validation_preferred_currency_invalid",
	"validation_generic_error",
] as const;

export type ValidationErrorKey = typeof KNOWN_VALIDATION_KEYS[number];

export function isKnownValidationKey(v: string | null | undefined): v is ValidationErrorKey {
	if (!v) return false;
	return (KNOWN_VALIDATION_KEYS as readonly string[]).includes(v);
}
